require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IrregularVerbsController do

  # This should return the minimal set of attributes required to create a valid
  # IrregularVerb. As you add validations to IrregularVerb, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IrregularVerbsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all irregular_verbs as @irregular_verbs" do
      irregular_verb = IrregularVerb.create! valid_attributes
      get :index, {}, valid_session
      assigns(:irregular_verbs).should eq([irregular_verb])
    end
  end

  describe "GET show" do
    it "assigns the requested irregular_verb as @irregular_verb" do
      irregular_verb = IrregularVerb.create! valid_attributes
      get :show, {:id => irregular_verb.to_param}, valid_session
      assigns(:irregular_verb).should eq(irregular_verb)
    end
  end

  describe "GET new" do
    it "assigns a new irregular_verb as @irregular_verb" do
      get :new, {}, valid_session
      assigns(:irregular_verb).should be_a_new(IrregularVerb)
    end
  end

  describe "GET edit" do
    it "assigns the requested irregular_verb as @irregular_verb" do
      irregular_verb = IrregularVerb.create! valid_attributes
      get :edit, {:id => irregular_verb.to_param}, valid_session
      assigns(:irregular_verb).should eq(irregular_verb)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new IrregularVerb" do
        expect {
          post :create, {:irregular_verb => valid_attributes}, valid_session
        }.to change(IrregularVerb, :count).by(1)
      end

      it "assigns a newly created irregular_verb as @irregular_verb" do
        post :create, {:irregular_verb => valid_attributes}, valid_session
        assigns(:irregular_verb).should be_a(IrregularVerb)
        assigns(:irregular_verb).should be_persisted
      end

      it "redirects to the created irregular_verb" do
        post :create, {:irregular_verb => valid_attributes}, valid_session
        response.should redirect_to(IrregularVerb.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved irregular_verb as @irregular_verb" do
        # Trigger the behavior that occurs when invalid params are submitted
        IrregularVerb.any_instance.stub(:save).and_return(false)
        post :create, {:irregular_verb => {}}, valid_session
        assigns(:irregular_verb).should be_a_new(IrregularVerb)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        IrregularVerb.any_instance.stub(:save).and_return(false)
        post :create, {:irregular_verb => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested irregular_verb" do
        irregular_verb = IrregularVerb.create! valid_attributes
        # Assuming there are no other irregular_verbs in the database, this
        # specifies that the IrregularVerb created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        IrregularVerb.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => irregular_verb.to_param, :irregular_verb => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested irregular_verb as @irregular_verb" do
        irregular_verb = IrregularVerb.create! valid_attributes
        put :update, {:id => irregular_verb.to_param, :irregular_verb => valid_attributes}, valid_session
        assigns(:irregular_verb).should eq(irregular_verb)
      end

      it "redirects to the irregular_verb" do
        irregular_verb = IrregularVerb.create! valid_attributes
        put :update, {:id => irregular_verb.to_param, :irregular_verb => valid_attributes}, valid_session
        response.should redirect_to(irregular_verb)
      end
    end

    describe "with invalid params" do
      it "assigns the irregular_verb as @irregular_verb" do
        irregular_verb = IrregularVerb.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IrregularVerb.any_instance.stub(:save).and_return(false)
        put :update, {:id => irregular_verb.to_param, :irregular_verb => {}}, valid_session
        assigns(:irregular_verb).should eq(irregular_verb)
      end

      it "re-renders the 'edit' template" do
        irregular_verb = IrregularVerb.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IrregularVerb.any_instance.stub(:save).and_return(false)
        put :update, {:id => irregular_verb.to_param, :irregular_verb => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested irregular_verb" do
      irregular_verb = IrregularVerb.create! valid_attributes
      expect {
        delete :destroy, {:id => irregular_verb.to_param}, valid_session
      }.to change(IrregularVerb, :count).by(-1)
    end

    it "redirects to the irregular_verbs list" do
      irregular_verb = IrregularVerb.create! valid_attributes
      delete :destroy, {:id => irregular_verb.to_param}, valid_session
      response.should redirect_to(irregular_verbs_url)
    end
  end

end
