require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VerbTestsController do

  # This should return the minimal set of attributes required to create a valid
  # VerbTest. As you add validations to VerbTest, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VerbTestsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all verb_tests as @verb_tests" do
      verb_test = VerbTest.create! valid_attributes
      get :index, {}, valid_session
      assigns(:verb_tests).should eq([verb_test])
    end
  end

  describe "GET show" do
    it "assigns the requested verb_test as @verb_test" do
      verb_test = VerbTest.create! valid_attributes
      get :show, {:id => verb_test.to_param}, valid_session
      assigns(:verb_test).should eq(verb_test)
    end
  end

  describe "GET new" do
    it "assigns a new verb_test as @verb_test" do
      get :new, {}, valid_session
      assigns(:verb_test).should be_a_new(VerbTest)
    end
  end

  describe "GET edit" do
    it "assigns the requested verb_test as @verb_test" do
      verb_test = VerbTest.create! valid_attributes
      get :edit, {:id => verb_test.to_param}, valid_session
      assigns(:verb_test).should eq(verb_test)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new VerbTest" do
        expect {
          post :create, {:verb_test => valid_attributes}, valid_session
        }.to change(VerbTest, :count).by(1)
      end

      it "assigns a newly created verb_test as @verb_test" do
        post :create, {:verb_test => valid_attributes}, valid_session
        assigns(:verb_test).should be_a(VerbTest)
        assigns(:verb_test).should be_persisted
      end

      it "redirects to the created verb_test" do
        post :create, {:verb_test => valid_attributes}, valid_session
        response.should redirect_to(VerbTest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved verb_test as @verb_test" do
        # Trigger the behavior that occurs when invalid params are submitted
        VerbTest.any_instance.stub(:save).and_return(false)
        post :create, {:verb_test => {}}, valid_session
        assigns(:verb_test).should be_a_new(VerbTest)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        VerbTest.any_instance.stub(:save).and_return(false)
        post :create, {:verb_test => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested verb_test" do
        verb_test = VerbTest.create! valid_attributes
        # Assuming there are no other verb_tests in the database, this
        # specifies that the VerbTest created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        VerbTest.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => verb_test.to_param, :verb_test => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested verb_test as @verb_test" do
        verb_test = VerbTest.create! valid_attributes
        put :update, {:id => verb_test.to_param, :verb_test => valid_attributes}, valid_session
        assigns(:verb_test).should eq(verb_test)
      end

      it "redirects to the verb_test" do
        verb_test = VerbTest.create! valid_attributes
        put :update, {:id => verb_test.to_param, :verb_test => valid_attributes}, valid_session
        response.should redirect_to(verb_test)
      end
    end

    describe "with invalid params" do
      it "assigns the verb_test as @verb_test" do
        verb_test = VerbTest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VerbTest.any_instance.stub(:save).and_return(false)
        put :update, {:id => verb_test.to_param, :verb_test => {}}, valid_session
        assigns(:verb_test).should eq(verb_test)
      end

      it "re-renders the 'edit' template" do
        verb_test = VerbTest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VerbTest.any_instance.stub(:save).and_return(false)
        put :update, {:id => verb_test.to_param, :verb_test => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested verb_test" do
      verb_test = VerbTest.create! valid_attributes
      expect {
        delete :destroy, {:id => verb_test.to_param}, valid_session
      }.to change(VerbTest, :count).by(-1)
    end

    it "redirects to the verb_tests list" do
      verb_test = VerbTest.create! valid_attributes
      delete :destroy, {:id => verb_test.to_param}, valid_session
      response.should redirect_to(verb_tests_url)
    end
  end

end
