source 'http://rubygems.org'

gem 'rails', '3.2.1'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', "  ~> 3.2.3"
  gem 'coffee-rails', "~> 3.2.1"
  gem 'uglifier', ">= 1.0.3"
end

gem 'jquery-rails'

# Use unicorn as the web server
# gem 'unicorn'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :development, :test do
  gem 'rspec-rails', '~> 2.8.1'
  gem 'cucumber', '~> 1.1.3'
  gem 'cucumber-rails','1.2.1'
  gem 'capybara', '~> 1.1.2'
  gem 'launchy'
  gem 'headless'        
  gem 'autotest'
  gem 'factory_girl'
  gem 'factory_girl_rails' , :require => false
  gem 'database_cleaner'
  gem 'jasmine'      
  gem 'guard-rspec'
  gem 'guard-cucumber'
  gem 'spork', '> 0.9.0.rc'
  gem 'guard-spork'
  if RUBY_PLATFORM.downcase.include?('darwin')
    gem 'rb-fsevent'
    gem 'growl' # also install growlnotify from the Extras/growlnotify/growlnotify.pkg in Growl disk image
  end 
end
group :test do
  gem 'turn', :require => false
  gem 'fuubar'
  gem 'simplecov', :require => false
  gem 'simplecov-rcov', :require => false
  gem 'ci_reporter'
  gem 'rr'
end
